- attributes/default.rb
- recipes/default.rb
- templates/default/ec2init_config.ini.erb
- templates/default/generate_elasticsearch_certs.sh.erb
- templates/default/init_hops-ca.sh.erb
[init_ca] Fix bugs and re-generate elastic certificates
[init_ca] Add certs dir to ec2init conf
[init_ca] Updates for 1.2
[init_ca] Increament ec2-init version
[init_ca] Fix
[init_ca] Fix template file
> [init_ca] Initialize Hops CA script

- recipes/install.rb
- templates/default/generate_glassfish_internal_x509.sh.erb
Fixes https://github.com/logicalclocks/hopsworks-cloud/issues/505
> [regenerate_internal] Shell script to facilitate regeneration of Hopsworks internal endpoint certificate

- attributes/default.rb
- files/default/config.json
- metadata.rb
- recipes/default.rb
- templates/default/cloud-environment.yml.erb
Tests: https://github.com/logicalclocks/hops-testing-ee/pull/127
> [HOPSWORKS-1902] Add support for managed docker registries

- attributes/default.rb
- templates/default/deploy2glassfish_hook.sh.erb
[cloud_domain_name] Change instance domain name regex
Fixes https://github.com/logicalclocks/hopsworks-cloud/issues/537
> [cloud_domain_name] Change hosted zone

- attributes/default.rb
- metadata.rb
- recipes/default.rb
- recipes/install.rb
- templates/default/ec2init_config.ini.erb
- templates/default/unmanaged-ec2init.service.erb
- templates/default/unmanaged_ec2init.sh.erb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-2042
> [unmanaged_localhost] Initialize unmanaged Instance

- attributes/default.rb
- metadata.rb
- recipes/default.rb
- recipes/install.rb
- templates/default/ec2init_config.ini.erb
- templates/default/unmanaged-ec2init.service.erb
- templates/default/unmanaged_ec2init.sh.erb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-2042
> Initialize unmanaged Instance (#25)

- attributes/default.rb
- templates/default/ec2init_config.ini.erb
* [gpu] Template nvidia download url to ec2-init configuration
* [gpu] Get nvidia packages download url from configuration
> [gpu] Gpu support (#27)

- attributes/default.rb
- metadata.rb
- recipes/default.rb
- recipes/install.rb
- templates/default/aws_agent_config.json.erb
https://github.com/logicalclocks/hopsworks-cloud/issues/1092
> [cw_agent] Install CloudWatch agent

- recipes/install.rb
- templates/default/unmanaged_ec2init.sh.erb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-2311
> [HOPSWORKS-2311] Template required parameters for unmanaged ec2-init

- recipes/install.rb
- templates/default/unmanaged_ec2init.sh.erb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-2311
> [HOPSWORKS-2311] Template required parameters for unmanaged ec2-init 

- recipes/default.rb
fixes https://github.com/logicalclocks/hopsworks-cloud/issues/1525
> install az command on azure nodes

- attributes/default.rb
- metadata.rb
- templates/default/ec2init_config.ini.erb
* [ndb_memory] Add attribute for NDB DataMemory multiplier
* [ndb_memory] Change NDB DataMemory multiplier
> [ndb_datamemory] [ndb_memory] Add attribute for NDB DataMemory multiplier (#44)

- templates/default/ndb-agent/join_hopsworks_cluster.sh.erb
Template Cloud provider instead of hardcoding it
> [rondb_azure] Template the cloud provider

- attributes/default.rb
- metadata.rb
- recipes/install.rb
- templates/default/ec2init_config.ini.erb
[HOPSWORKS-2578] Add ec2-init log file under data volume
https://logicalclocks.atlassian.net/browse/HOPSWORKS-2578
[HOPSWORKS-2578]: https://logicalclocks.atlassian.net/browse/HOPSWORKS-2578
> [HOPSWORKS-2578] Create ec2-init check files under data directory

- recipes/prepare_upgrade.rb
- templates/default/ec2init_config.ini.erb
- templates/default/expat-site.xml.erb
- templates/default/run_expat.sh.erb
Fixes https://github.com/logicalclocks/hopsworks-cloud/issues/2147
> Fixes for upgrade from 2.2 to 2.3

- templates/default/ndb-agent/join_hopsworks_cluster.sh.erb
Fixes https://github.com/logicalclocks/ndb-agent/issues/13
> [NDB-AGENT-13] Template Azure search domain in RonDB join cluster script

- templates/default/ec2init_config.ini.erb
Fixes https://github.com/logicalclocks/hopsworks-cloud/issues/1833
> [HOPSWORKS-CLOUD-1833] Add a script to reindex base indices

- templates/default/expat-site.xml.erb
Fixes https://github.com/logicalclocks/ec2-init/issues/263
> Create index template and index pattern for services log on upgrade

- attributes/default.rb
Fixes https://github.com/logicalclocks/ec2-init/issues/278
> Bump up ec2-init version to 0.12

- templates/default/ndb-agent/config.yml.erb
> Changed address to hostname

- recipes/metrics_daemon.rb
Fixes https://logicalclocks.atlassian.net/browse/HOPSWORKS-2924
> [HOPSWORKS-2924] Fix file ownership of metrics collector daemon

- recipes/prepare_upgrade.rb
- templates/default/ec2init_config.ini.erb
Part of https://github.com/logicalclocks/ec2-init/issues/296
> [HOPSWORKS-2896] append - keep airflow image locally for upgrade

- templates/default/ndb-agent/join_hopsworks_cluster.sh.erb
Resolves https://github.com/logicalclocks/hopsworks-cloud/issues/2681
> [HOPSWORKS-CLOUD] Change search domain attribute name

- templates/default/cloud-environment.yml.erb
> [CLOUD-CHEF-114] add google-cloud-storage to python env

- templates/default/cloud-environment.yml.erb
Fixes https://github.com/logicalclocks/ec2-init/issues/340
> Pin azure dependencies

- files/default/ndb_templates/ndb_config.ini
Fixes https://github.com/logicalclocks/cloud-tickets/issues/41
> [HOPSWORKS-CLOUD-41] Temporarily decrease the size of table spaces and logfiles

- files/default/ndb_templates/ndb_config.ini
Fixes #122 
Merge with https://github.com/logicalclocks/ndb-agent/pull/126
> Make all Mysqlds & Apis Configurable by Ndb-Agent

- templates/default/cloud-environment.yml.erb
Fixes https://github.com/logicalclocks/cloud-tickets/issues/63
> Pin protobuf version to 3.19.4

- templates/default/deploy2glassfish_hook.sh.erb
Needed by https://github.com/logicalclocks/hopsworks-cloud/issues/3123
> [HOPSWORKS-CLOUD-3123] Allow for custom Hosted Zones

- attributes/default.rb
Linked to https://github.com/logicalclocks/ndb-agent/pull/221
> [NDB-AGENT-220] Change ndb-agent version scheme

- templates/default/cloud-environment.yml.erb
Fixes https://hopsworks.atlassian.net/browse/CLOUD-75
> [CLOUD-75] update conda cloud env to python 3.8

- attributes/default.rb
https://hopsworks.atlassian.net/browse/CLOUD-242
> [CLOUD-242] Release ndb-agent

- templates/default/ndb-agent/config.yml.erb
https://hopsworks.atlassian.net/browse/CLOUD-308
> [CLOUD-308] Add ndb-agent configuration property for mysqld start timeout

- attributes/default.rb
https://hopsworks.atlassian.net/browse/CLOUD-353
> [CLOUD-353] Bumpup ndb-agent version

- attributes/default.rb
https://hopsworks.atlassian.net/browse/RONDB-235
> [RONDB-235] ndb-agent patch version

- templates/default/cloud-environment.yml.erb
Fixes https://hopsworks.atlassian.net/browse/CLOUD-370
> [CLOUD-370] add library to be able to check bucket permissions

- templates/default/cloud-environment.yml.erb
Reverts logicalclocks/cloud-chef#155
> Revert "addendum CLOUD-370 upgrade dependencies"

- templates/default/cloud-environment.yml.erb
Reverts logicalclocks/cloud-chef#154
> Revert "[CLOUD-370] add library to be able to check bucket permissions"

- templates/default/cloud-environment.yml.erb
Fixes https://hopsworks.atlassian.net/browse/CLOUD-370
> [CLOUD-370] add library to test blob storage permissions

- templates/default/ndb-agent/config.yml.erb
Fixes https://hopsworks.atlassian.net/browse/CLOUD-474
> [CLOUD-474] Add configurable number of extra mysqld slots

- attributes/default.rb
Fixes https://hopsworks.atlassian.net/browse/CLOUD-547
> [CLOUD-547] Bump ec2-init version to 0.16

- attributes/default.rb
https://hopsworks.atlassian.net/browse/CLOUD-630
> [CLOUD-630] Bump ndb-agent version

- attributes/default.rb
https://hopsworks.atlassian.net/browse/CLOUD-630
> [CLOUD-630-3.3] Release ndb-agent 0.8.0

- attributes/default.rb
https://hopsworks.atlassian.net/browse/RONDB-436
> [RONDB-436] Bump ndb-agent patch version

- attributes/default.rb
https://hopsworks.atlassian.net/browse/RONDB-434
> [RONDB-434_3.3] Bump ndb-agent version

- attributes/default.rb
Fixes https://hopsworks.atlassian.net/browse/CLOUD-639
> [CLOUD-639] Use the latest aws cli version

- attributes/default.rb
Fixes https://hopsworks.atlassian.net/browse/CLOUD-661
> [CLOUD-661] Bump ec2-init version to 0.18

- attributes/default.rb
https://hopsworks.atlassian.net/browse/RONDB-515
> [RONDB-515_3.4] Release ndb-agent

- attributes/default.rb
https://hopsworks.atlassian.net/browse/RONDB-515
> [RONDB-515] Bump dev version

- attributes/default.rb
Fixes https://hopsworks.atlassian.net/browse/CLOUD-689
> [CLOUD-689] Bump ec2-init version to 0.19

- attributes/default.rb
Fixes https://hopsworks.atlassian.net/browse/RONDB-550
> [RONDB-550] Release ndb-agent 0.10.0

- attributes/default.rb
Fixes https://hopsworks.atlassian.net/browse/RONDB-550
> [RONDB-550] Bump ndb-agent version to 0.11.0-SNAPSHOT

- attributes/default.rb
- files/default/smarter-device-manager-plugin.yml
- recipes/default.rb
- recipes/install.rb
- templates/default/cloud-environment.yml.erb
Fixes https://hopsworks.atlassian.net/browse/CLOUD-97
> [CLOUD-97] Add support for GCR/GKE

- attributes/default.rb
Fixes https://hopsworks.atlassian.net/browse/CLOUD-710
> [CLOUD-710] Bump ec2-init version to 0.20

- attributes/default.rb
Fixes https://hopsworks.atlassian.net/browse/RONDB-639
> [RONDB-639] Use release ndb-agent version 0.11.0

- attributes/default.rb
Fixes https://hopsworks.atlassian.net/browse/RONDB-639
> [RONDB-639] Bump ndb-agent version 0.12.0-SNAPSHOT

- recipes/default.rb
- recipes/install.rb
https://hopsworks.atlassian.net/browse/CLOUD-721
> [CLOUD-721-amend] Install Python3.11 for Centos and virtualenv through pip as the package coming from Centos is too old

- recipes/default.rb
- recipes/install.rb
https://hopsworks.atlassian.net/browse/CLOUD-721
> [CLOUD-721] Use pyenv for Cloud Python3.11

- recipes/install.rb
https://hopsworks.atlassian.net/browse/CLOUD-721
> [CLOUD-721-amend] Install required packages to install PyEnv

- recipes/install.rb
https://hopsworks.atlassian.net/browse/CLOUD-721
> [CLOUD-721-amend] Install more packages for pyenv

- attributes/default.rb
- templates/default/ec2init_config.ini.erb
https://hopsworks.atlassian.net/browse/CLOUD-734
> [CLOUD-734] Template airflow user credentials used to generate API key

- attributes/default.rb
https://hopsworks.atlassian.net/browse/CLOUD-751
> [CLOUD-751] Bump version

- attributes/default.rb
https://hopsworks.atlassian.net/browse/CLOUD-773
> [CLOUD-773] Bump ec2-init version

- attributes/default.rb
https://hopsworks.atlassian.net/browse/CLOUD-773
> [CLOUD-773] Bump ec2-init version (#211)
